version: '3.3'

services:
  mongo:
    image: mongo:latest
    container_name: chatbot-system_mongo_1
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=chatbot
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://admin:password123@mongo:27017/chatbot?authSource=admin&directConnection=true
      - JWT_SECRET=your_jwt_secret_key_here
      - ADMIN_EMAIL=admin@yeditepe.edu.tr
      - PORT=5000
      - NODE_ENV=production
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://34.136.154.58:5000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: 